[package]
name = "mirakurun_client"
version = "0.1.0"
authors = ["Kazuki Kuroda <kazukuro0824+dev@gmail.com>", "OpenAPI Generator team and contributors"]
edition = "2018"
license = "Apache-2.0"
description = "A Rust client library for Mirakurun."

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
url = "^2.2"
[dependencies.reqwest]
version = "^0.11"
features = ["json", "multipart"]

[dev-dependencies]
