/*
 * Mirakurun
 *
 * DVR Tuner Server Service for Chinachu Air.
 *
 * The version of the OpenAPI document: 3.9.0-beta.20
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChannelType {
    #[serde(rename = "GR")]
    GR,
    #[serde(rename = "BS")]
    BS,
    #[serde(rename = "CS")]
    CS,
    #[serde(rename = "SKY")]
    SKY,

}

impl ToString for ChannelType {
    fn to_string(&self) -> String {
        match self {
            Self::GR => String::from("GR"),
            Self::BS => String::from("BS"),
            Self::CS => String::from("CS"),
            Self::SKY => String::from("SKY"),
        }
    }
}




