/*
 * Mirakurun
 *
 * DVR Tuner Server Service for Chinachu Air.
 *
 * The version of the OpenAPI document: 3.9.0-beta.7
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigChannelsItem {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub _type: crate::models::ChannelType,
    #[serde(rename = "channel")]
    pub channel: String,
    #[serde(rename = "serviceId", skip_serializing_if = "Option::is_none")]
    pub service_id: Option<i32>,
    #[serde(rename = "satellite", skip_serializing_if = "Option::is_none")]
    pub satellite: Option<String>,
    #[serde(rename = "space", skip_serializing_if = "Option::is_none")]
    pub space: Option<i32>,
    #[serde(rename = "freq", skip_serializing_if = "Option::is_none")]
    pub freq: Option<f32>,
    #[serde(rename = "polarity", skip_serializing_if = "Option::is_none")]
    pub polarity: Option<Polarity>,
    #[serde(rename = "isDisabled", skip_serializing_if = "Option::is_none")]
    pub is_disabled: Option<bool>,
}

impl ConfigChannelsItem {
    pub fn new(name: String, _type: crate::models::ChannelType, channel: String) -> ConfigChannelsItem {
        ConfigChannelsItem {
            name,
            _type,
            channel,
            service_id: None,
            satellite: None,
            space: None,
            freq: None,
            polarity: None,
            is_disabled: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Polarity {
    #[serde(rename = "H")]
    H,
    #[serde(rename = "V")]
    V,
}

