/*
 * Mirakurun
 *
 * DVR Tuner Server Service for Chinachu Air.
 *
 * The version of the OpenAPI document: 3.9.0-beta.20
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConfigServer {
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    #[serde(rename = "disableIPv6", skip_serializing_if = "Option::is_none")]
    pub disable_ipv6: Option<bool>,
    #[serde(rename = "logLevel", skip_serializing_if = "Option::is_none")]
    pub log_level: Option<i32>,
    #[serde(rename = "maxLogHistory", skip_serializing_if = "Option::is_none")]
    pub max_log_history: Option<i32>,
    #[serde(rename = "maxBufferBytesBeforeReady", skip_serializing_if = "Option::is_none")]
    pub max_buffer_bytes_before_ready: Option<i32>,
    #[serde(rename = "eventEndTimeout", skip_serializing_if = "Option::is_none")]
    pub event_end_timeout: Option<i32>,
    #[serde(rename = "programGCInterval", skip_serializing_if = "Option::is_none")]
    pub program_gc_interval: Option<i32>,
    #[serde(rename = "epgGatheringInterval", skip_serializing_if = "Option::is_none")]
    pub epg_gathering_interval: Option<i32>,
    #[serde(rename = "epgRetrievalTime", skip_serializing_if = "Option::is_none")]
    pub epg_retrieval_time: Option<i32>,
    #[serde(rename = "logoDataInterval", skip_serializing_if = "Option::is_none")]
    pub logo_data_interval: Option<i32>,
    #[serde(rename = "disableEITParsing", skip_serializing_if = "Option::is_none")]
    pub disable_eit_parsing: Option<bool>,
    #[serde(rename = "disableWebUI", skip_serializing_if = "Option::is_none")]
    pub disable_web_ui: Option<bool>,
}

impl ConfigServer {
    pub fn new() -> ConfigServer {
        ConfigServer {
            path: None,
            port: None,
            hostname: None,
            disable_ipv6: None,
            log_level: None,
            max_log_history: None,
            max_buffer_bytes_before_ready: None,
            event_end_timeout: None,
            program_gc_interval: None,
            epg_gathering_interval: None,
            epg_retrieval_time: None,
            logo_data_interval: None,
            disable_eit_parsing: None,
            disable_web_ui: None,
        }
    }
}


