/*
 * Mirakurun
 *
 * DVR Tuner Server Service for Chinachu Air.
 *
 * The version of the OpenAPI document: 3.9.0-beta.7
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConfigTunersItem {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "types")]
    pub types: Vec<crate::models::ChannelType>,
    #[serde(rename = "command", skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
    #[serde(rename = "dvbDevicePath", skip_serializing_if = "Option::is_none")]
    pub dvb_device_path: Option<String>,
    #[serde(rename = "remoteMirakurunHost", skip_serializing_if = "Option::is_none")]
    pub remote_mirakurun_host: Option<String>,
    #[serde(rename = "remoteMirakurunPort", skip_serializing_if = "Option::is_none")]
    pub remote_mirakurun_port: Option<i32>,
    #[serde(rename = "remoteMirakurunDecoder", skip_serializing_if = "Option::is_none")]
    pub remote_mirakurun_decoder: Option<bool>,
    #[serde(rename = "decoder", skip_serializing_if = "Option::is_none")]
    pub decoder: Option<String>,
    #[serde(rename = "isDisabled", skip_serializing_if = "Option::is_none")]
    pub is_disabled: Option<bool>,
}

impl ConfigTunersItem {
    pub fn new(name: String, types: Vec<crate::models::ChannelType>) -> ConfigTunersItem {
        ConfigTunersItem {
            name,
            types,
            command: None,
            dvb_device_path: None,
            remote_mirakurun_host: None,
            remote_mirakurun_port: None,
            remote_mirakurun_decoder: None,
            decoder: None,
            is_disabled: None,
        }
    }
}


