/*
 * Mirakurun
 *
 * DVR Tuner Server for Japanese TV.
 *
 * The version of the OpenAPI document: 3.9.0-rc.2
 * 
 * Generated by: https://openapi-generator.tech
 */


use chrono::{DateTime, Utc};
use chrono::serde::ts_milliseconds;


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Event {
    #[serde(rename = "resource")]
    pub resource: crate::models::EventResource,
    #[serde(rename = "type")]
    pub _type: crate::models::EventType,
    #[serde(rename = "data")]
    pub data: serde_json::Value,
    #[serde(rename = "time", with = "ts_milliseconds")]
    pub time: DateTime<Utc>,
}

impl Event {
    pub fn new(resource: crate::models::EventResource, _type: crate::models::EventType, data: serde_json::Value, time: DateTime<Utc>) -> Event {
        Event {
            resource,
            _type,
            data,
            time,
        }
    }
}


