/*
 * Mirakurun
 *
 * DVR Tuner Server Service for Chinachu Air.
 *
 * The version of the OpenAPI document: 3.9.0-beta.20
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Event {
    #[serde(rename = "resource")]
    pub resource: crate::models::EventResource,
    #[serde(rename = "type")]
    pub _type: crate::models::EventType,
    #[serde(rename = "data")]
    pub data: serde_json::Value,
    #[serde(rename = "time")]
    pub time: i32,
}

impl Event {
    pub fn new(resource: crate::models::EventResource, _type: crate::models::EventType, data: serde_json::Value, time: i32) -> Event {
        Event {
            resource,
            _type,
            data,
            time,
        }
    }
}


