/*
 * Mirakurun
 *
 * DVR Tuner Server for Japanese TV.
 *
 * The version of the OpenAPI document: 3.9.0-rc.2
 *
 * Generated by: https://openapi-generator.tech
 */

use chrono::serde::ts_milliseconds;
use chrono::{DateTime, Utc};
use crate::models::{Program, Service, TunerDevice};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Event {
    #[serde(rename = "type")]
    pub r#type: crate::models::EventType,
    #[serde(rename = "data")]
    pub data: EventContent,
    #[serde(rename = "time", with = "ts_milliseconds")]
    pub time: DateTime<Utc>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag="resource", content="data")]
pub enum EventContent {
    #[serde(rename = "program")]
    Program(Program),
    #[serde(rename = "service")]
    Service(Service),
    #[serde(rename = "tuner")]
    Tuner(TunerDevice)
}
