/*
 * Mirakurun
 *
 * DVR Tuner Server for Japanese TV.
 *
 * The version of the OpenAPI document: 3.9.0-rc.2
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProgramVideoType {
    #[serde(rename = "mpeg2")]
    Mpeg2,
    #[serde(rename = "h.264")]
    H264,
    #[serde(rename = "h.265")]
    H265,

}

impl ToString for ProgramVideoType {
    fn to_string(&self) -> String {
        match self {
            Self::Mpeg2 => String::from("mpeg2"),
            Self::H264 => String::from("h.264"),
            Self::H265 => String::from("h.265"),
        }
    }
}

impl Default for ProgramVideoType {
    fn default() -> ProgramVideoType {
        Self::Mpeg2
    }
}




