/*
 * Mirakurun
 *
 * DVR Tuner Server Service for Chinachu Air.
 *
 * The version of the OpenAPI document: 3.9.0-beta.20
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProgramSeries {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "repeat", skip_serializing_if = "Option::is_none")]
    pub repeat: Option<i32>,
    #[serde(rename = "pattern", skip_serializing_if = "Option::is_none")]
    pub pattern: Option<i32>,
    #[serde(rename = "expiresAt", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<i32>,
    #[serde(rename = "episode", skip_serializing_if = "Option::is_none")]
    pub episode: Option<i32>,
    #[serde(rename = "lastEpisode", skip_serializing_if = "Option::is_none")]
    pub last_episode: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl ProgramSeries {
    pub fn new() -> ProgramSeries {
        ProgramSeries {
            id: None,
            repeat: None,
            pattern: None,
            expires_at: None,
            episode: None,
            last_episode: None,
            name: None,
        }
    }
}


