/*
 * Mirakurun
 *
 * DVR Tuner Server Service for Chinachu Air.
 *
 * The version of the OpenAPI document: 3.9.0-beta.20
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProgramAudios {
    #[serde(rename = "componentType", skip_serializing_if = "Option::is_none")]
    pub component_type: Option<i32>,
    #[serde(rename = "componentTag", skip_serializing_if = "Option::is_none")]
    pub component_tag: Option<i32>,
    #[serde(rename = "isMain", skip_serializing_if = "Option::is_none")]
    pub is_main: Option<bool>,
    //TODO: serde_repr is needed to avoid ExpectedSomeValue error
    #[serde(rename = "samplingRate", skip_serializing_if = "Option::is_none", skip_deserializing)]
    pub sampling_rate: Option<crate::models::ProgramAudioSamplingRate>,
    #[serde(rename = "langs", skip_serializing_if = "Option::is_none")]
    pub langs: Option<Vec<Langs>>,
}

impl ProgramAudios {
    pub fn new() -> ProgramAudios {
        ProgramAudios {
            component_type: None,
            component_tag: None,
            is_main: None,
            sampling_rate: None,
            langs: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Langs {
    #[serde(rename = "jpn")]
    Jpn,
    #[serde(rename = "eng")]
    Eng,
    #[serde(rename = "deu")]
    Deu,
    #[serde(rename = "fra")]
    Fra,
    #[serde(rename = "ita")]
    Ita,
    #[serde(rename = "rus")]
    Rus,
    #[serde(rename = "zho")]
    Zho,
    #[serde(rename = "kor")]
    Kor,
    #[serde(rename = "spa")]
    Spa,
    #[serde(rename = "etc")]
    Etc,
}

