/*
 * Mirakurun
 *
 * DVR Tuner Server for Japanese TV.
 *
 * The version of the OpenAPI document: 3.9.0-rc.2
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProgramAudioSamplingRate {
    #[serde(rename = "16000")]
    Variant16000,
    #[serde(rename = "22050")]
    Variant22050,
    #[serde(rename = "24000")]
    Variant24000,
    #[serde(rename = "32000")]
    Variant32000,
    #[serde(rename = "44100")]
    Variant44100,
    #[serde(rename = "48000")]
    Variant48000,

}

impl ToString for ProgramAudioSamplingRate {
    fn to_string(&self) -> String {
        match self {
            Self::Variant16000 => String::from("16000"),
            Self::Variant22050 => String::from("22050"),
            Self::Variant24000 => String::from("24000"),
            Self::Variant32000 => String::from("32000"),
            Self::Variant44100 => String::from("44100"),
            Self::Variant48000 => String::from("48000"),
        }
    }
}

impl Default for ProgramAudioSamplingRate {
    fn default() -> ProgramAudioSamplingRate {
        Self::Variant16000
    }
}




