/*
 * Mirakurun
 *
 * DVR Tuner Server for Japanese TV.
 *
 * The version of the OpenAPI document: 3.9.0-rc.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde_repr::{Serialize_repr, Deserialize_repr};
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
#[repr(u32)]
pub enum ProgramAudioSamplingRate {
    #[serde(rename = "16000")]
    _16000 = 16000,
    #[serde(rename = "22050")]
    _22050 = 22050,
    #[serde(rename = "24000")]
    _24000 = 24000,
    #[serde(rename = "32000")]
    _32000 = 32000,
    #[serde(rename = "44100")]
    _44100 = 44100,
    #[serde(rename = "48000")]
    _48000 = 48000,

}

impl ToString for ProgramAudioSamplingRate {
    fn to_string(&self) -> String {
        match self {
            Self::_16000 => String::from("16000"),
            Self::_22050 => String::from("22050"),
            Self::_24000 => String::from("24000"),
            Self::_32000 => String::from("32000"),
            Self::_44100 => String::from("44100"),
            Self::_48000 => String::from("48000"),
        }
    }
}

impl Default for ProgramAudioSamplingRate {
    fn default() -> ProgramAudioSamplingRate {
        Self::_16000
    }
}




