/*
 * Mirakurun
 *
 * DVR Tuner Server for Japanese TV.
 *
 * The version of the OpenAPI document: 3.9.0-rc.2
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProgramVideoResolution {
    #[serde(rename = "240p")]
    Variant240p,
    #[serde(rename = "480i")]
    Variant480i,
    #[serde(rename = "480p")]
    Variant480p,
    #[serde(rename = "720p")]
    Variant720p,
    #[serde(rename = "1080i")]
    Variant1080i,
    #[serde(rename = "1080p")]
    Variant1080p,
    #[serde(rename = "2160p")]
    Variant2160p,
    #[serde(rename = "4320p")]
    Variant4320p,

}

impl ToString for ProgramVideoResolution {
    fn to_string(&self) -> String {
        match self {
            Self::Variant240p => String::from("240p"),
            Self::Variant480i => String::from("480i"),
            Self::Variant480p => String::from("480p"),
            Self::Variant720p => String::from("720p"),
            Self::Variant1080i => String::from("1080i"),
            Self::Variant1080p => String::from("1080p"),
            Self::Variant2160p => String::from("2160p"),
            Self::Variant4320p => String::from("4320p"),
        }
    }
}

impl Default for ProgramVideoResolution {
    fn default() -> ProgramVideoResolution {
        Self::Variant240p
    }
}




