/*
 * Mirakurun
 *
 * DVR Tuner Server Service for Chinachu Air.
 *
 * The version of the OpenAPI document: 3.9.0-beta.7
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProgramAudioSamplingRate {
    #[serde(rename = "16000")]
    _16000,
    #[serde(rename = "22050")]
    _22050,
    #[serde(rename = "24000")]
    _24000,
    #[serde(rename = "32000")]
    _32000,
    #[serde(rename = "44100")]
    _44100,
    #[serde(rename = "48000")]
    _48000,

}

impl ToString for ProgramAudioSamplingRate {
    fn to_string(&self) -> String {
        match self {
            Self::_16000 => String::from("16000"),
            Self::_22050 => String::from("22050"),
            Self::_24000 => String::from("24000"),
            Self::_32000 => String::from("32000"),
            Self::_44100 => String::from("44100"),
            Self::_48000 => String::from("48000"),
        }
    }
}




