/*
 * Mirakurun
 *
 * DVR Tuner Server Service for Chinachu Air.
 *
 * The version of the OpenAPI document: 3.9.0-beta.7
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProgramGenre {
    #[serde(rename = "lv1", skip_serializing_if = "Option::is_none")]
    pub lv1: Option<i32>,
    #[serde(rename = "lv2", skip_serializing_if = "Option::is_none")]
    pub lv2: Option<i32>,
    #[serde(rename = "un1", skip_serializing_if = "Option::is_none")]
    pub un1: Option<i32>,
    #[serde(rename = "un2", skip_serializing_if = "Option::is_none")]
    pub un2: Option<i32>,
}

impl ProgramGenre {
    pub fn new() -> ProgramGenre {
        ProgramGenre {
            lv1: None,
            lv2: None,
            un1: None,
            un2: None,
        }
    }
}


