/*
 * Mirakurun
 *
 * DVR Tuner Server for Japanese TV.
 *
 * The version of the OpenAPI document: 3.9.0-rc.2
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StatusProcessMemoryUsage {
    #[serde(rename = "rss", skip_serializing_if = "Option::is_none")]
    pub rss: Option<i32>,
    #[serde(rename = "heapTotal", skip_serializing_if = "Option::is_none")]
    pub heap_total: Option<i32>,
    #[serde(rename = "heapUsed", skip_serializing_if = "Option::is_none")]
    pub heap_used: Option<i32>,
}

impl StatusProcessMemoryUsage {
    pub fn new() -> StatusProcessMemoryUsage {
        StatusProcessMemoryUsage {
            rss: None,
            heap_total: None,
            heap_used: None,
        }
    }
}


