/*
 * Mirakurun
 *
 * DVR Tuner Server Service for Chinachu Air.
 *
 * The version of the OpenAPI document: 3.9.0-beta.7
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StatusTimerAccuracy {
    #[serde(rename = "last", skip_serializing_if = "Option::is_none")]
    pub last: Option<f32>,
    #[serde(rename = "m1", skip_serializing_if = "Option::is_none")]
    pub m1: Option<Box<crate::models::StatusTimerAccuracyM1>>,
    #[serde(rename = "m5", skip_serializing_if = "Option::is_none")]
    pub m5: Option<Box<crate::models::StatusTimerAccuracyM1>>,
    #[serde(rename = "m15", skip_serializing_if = "Option::is_none")]
    pub m15: Option<Box<crate::models::StatusTimerAccuracyM1>>,
}

impl StatusTimerAccuracy {
    pub fn new() -> StatusTimerAccuracy {
        StatusTimerAccuracy {
            last: None,
            m1: None,
            m5: None,
            m15: None,
        }
    }
}


