/*
 * Mirakurun
 *
 * DVR Tuner Server Service for Chinachu Air.
 *
 * The version of the OpenAPI document: 3.9.0-beta.7
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Status {
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<i32>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "process", skip_serializing_if = "Option::is_none")]
    pub process: Option<Box<crate::models::StatusProcess>>,
    #[serde(rename = "epg", skip_serializing_if = "Option::is_none")]
    pub epg: Option<Box<crate::models::StatusEpg>>,
    #[serde(rename = "rpcCount", skip_serializing_if = "Option::is_none")]
    pub rpc_count: Option<i32>,
    #[serde(rename = "streamCount", skip_serializing_if = "Option::is_none")]
    pub stream_count: Option<Box<crate::models::StatusStreamCount>>,
    #[serde(rename = "errorCount", skip_serializing_if = "Option::is_none")]
    pub error_count: Option<Box<crate::models::StatusErrorCount>>,
    #[serde(rename = "timerAccuracy", skip_serializing_if = "Option::is_none")]
    pub timer_accuracy: Option<Box<crate::models::StatusTimerAccuracy>>,
}

impl Status {
    pub fn new() -> Status {
        Status {
            time: None,
            version: None,
            process: None,
            epg: None,
            rpc_count: None,
            stream_count: None,
            error_count: None,
            timer_accuracy: None,
        }
    }
}


