/*
 * Mirakurun
 *
 * DVR Tuner Server for Japanese TV.
 *
 * The version of the OpenAPI document: 3.9.0-rc.2
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TunerUserStreamInfoValue {
    #[serde(rename = "packet")]
    pub packet: i32,
    #[serde(rename = "drop")]
    pub drop: i32,
}

impl TunerUserStreamInfoValue {
    pub fn new(packet: i32, drop: i32) -> TunerUserStreamInfoValue {
        TunerUserStreamInfoValue {
            packet,
            drop,
        }
    }
}


