/*
 * Mirakurun
 *
 * DVR Tuner Server Service for Chinachu Air.
 *
 * The version of the OpenAPI document: 3.9.0-beta.7
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TunerUserStreamInfo {
    #[serde(rename = "packet")]
    pub packet: i32,
    #[serde(rename = "drop")]
    pub drop: i32,
}

impl TunerUserStreamInfo {
    pub fn new(packet: i32, drop: i32) -> TunerUserStreamInfo {
        TunerUserStreamInfo {
            packet,
            drop,
        }
    }
}


