/*
 * Mirakurun
 *
 * DVR Tuner Server for Japanese TV.
 *
 * The version of the OpenAPI document: 3.9.0-rc.2
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TunerProcess {
    #[serde(rename = "pid")]
    pub pid: i32,
}

impl TunerProcess {
    pub fn new(pid: i32) -> TunerProcess {
        TunerProcess {
            pid,
        }
    }
}


