/*
 * Mirakurun
 *
 * DVR Tuner Server Service for Chinachu Air.
 *
 * The version of the OpenAPI document: 3.9.0-beta.7
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Version {
    #[serde(rename = "current", skip_serializing_if = "Option::is_none")]
    pub current: Option<String>,
    #[serde(rename = "latest", skip_serializing_if = "Option::is_none")]
    pub latest: Option<String>,
}

impl Version {
    pub fn new() -> Version {
        Version {
            current: None,
            latest: None,
        }
    }
}


